// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type Change struct {
	Seq      int64
	Entity   string
	EntityID string
	Op       string
	Revision *int64
	At       int64
}

type Domain struct {
	ID          string
	Description *string
	Layers      string
	Revision    int64
	CreatedAt   int64
}

type Edge struct {
	ID         int64
	SourceID   string
	TargetID   string
	Type       string
	Properties string
	Revision   int64
	CreatedAt  int64
}

type Node struct {
	ID         string
	Domain     string
	Layer      string
	Name       string
	ParentID   *string
	Summary    *string
	Properties string
	Revision   int64
	CreatedAt  int64
	UpdatedAt  int64
}
