// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
)

const appendChange = `-- name: AppendChange :exec
INSERT INTO changes(entity, entity_id, op, revision, at) VALUES (?, ?, ?, ?, ?)
`

type AppendChangeParams struct {
	Entity   string
	EntityID string
	Op       string
	Revision *int64
	At       int64
}

func (q *Queries) AppendChange(ctx context.Context, arg AppendChangeParams) error {
	_, err := q.db.ExecContext(ctx, appendChange,
		arg.Entity,
		arg.EntityID,
		arg.Op,
		arg.Revision,
		arg.At,
	)
	return err
}

const createDomain = `-- name: CreateDomain :exec
INSERT INTO domains(id, description, layers, revision, created_at)
VALUES (?, ?, ?, 1, ?)
`

type CreateDomainParams struct {
	ID          string
	Description *string
	Layers      string
	CreatedAt   int64
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) error {
	_, err := q.db.ExecContext(ctx, createDomain,
		arg.ID,
		arg.Description,
		arg.Layers,
		arg.CreatedAt,
	)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const getDomain = `-- name: GetDomain :one
SELECT id, description, layers, revision, created_at FROM domains WHERE id = ?
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Layers,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, description, layers, revision, created_at FROM domains ORDER BY id
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Layers,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
