// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"strings"
)

const addEdgeClaim = `-- name: AddEdgeClaim :exec
INSERT OR IGNORE INTO edge_claims(edge_id, source, claimed_at) VALUES (?, ?, ?)
`

type AddEdgeClaimParams struct {
	EdgeID    int64
	Source    string
	ClaimedAt int64
}

func (q *Queries) AddEdgeClaim(ctx context.Context, arg AddEdgeClaimParams) error {
	_, err := q.db.ExecContext(ctx, addEdgeClaim, arg.EdgeID, arg.Source, arg.ClaimedAt)
	return err
}

const appendChange = `-- name: AppendChange :exec
INSERT INTO changes(entity, entity_id, source, op, revision, at) VALUES (?, ?, ?, ?, ?, ?)
`

type AppendChangeParams struct {
	Entity   string
	EntityID string
	Source   *string
	Op       string
	Revision *int64
	At       int64
}

func (q *Queries) AppendChange(ctx context.Context, arg AppendChangeParams) error {
	_, err := q.db.ExecContext(ctx, appendChange,
		arg.Entity,
		arg.EntityID,
		arg.Source,
		arg.Op,
		arg.Revision,
		arg.At,
	)
	return err
}

const childrenOf = `-- name: ChildrenOf :many
SELECT id, domain, layer, name, parent_id, source, properties, revision, created_at, updated_at
FROM nodes WHERE parent_id = ? ORDER BY id
`

func (q *Queries) ChildrenOf(ctx context.Context, parentID *string) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, childrenOf, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Layer,
			&i.Name,
			&i.ParentID,
			&i.Source,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEdgeClaims = `-- name: CountEdgeClaims :one
SELECT COUNT(*) AS n FROM edge_claims WHERE edge_id = ?
`

func (q *Queries) CountEdgeClaims(ctx context.Context, edgeID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEdgeClaims, edgeID)
	var n int64
	err := row.Scan(&n)
	return n, err
}

const createDomain = `-- name: CreateDomain :exec
INSERT INTO domains(id, description, layers, revision, created_at)
VALUES (?, ?, ?, 1, ?)
`

type CreateDomainParams struct {
	ID          string
	Description *string
	Layers      string
	CreatedAt   int64
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) error {
	_, err := q.db.ExecContext(ctx, createDomain,
		arg.ID,
		arg.Description,
		arg.Layers,
		arg.CreatedAt,
	)
	return err
}

const createNode = `-- name: CreateNode :exec
INSERT INTO nodes(id, domain, layer, name, parent_id, source, properties, revision, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?)
`

type CreateNodeParams struct {
	ID         string
	Domain     string
	Layer      string
	Name       string
	ParentID   *string
	Source     string
	Properties string
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) error {
	_, err := q.db.ExecContext(ctx, createNode,
		arg.ID,
		arg.Domain,
		arg.Layer,
		arg.Name,
		arg.ParentID,
		arg.Source,
		arg.Properties,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains WHERE id = ?
`

func (q *Queries) DeleteDomain(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDomain, id)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM edges WHERE id = ?
`

func (q *Queries) DeleteEdge(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEdge, id)
	return err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const deleteSource = `-- name: DeleteSource :exec
DELETE FROM sources WHERE id = ?
`

func (q *Queries) DeleteSource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSource, id)
	return err
}

const edgeIDsClaimedBy = `-- name: EdgeIDsClaimedBy :many
SELECT edge_id FROM edge_claims WHERE source = ? ORDER BY edge_id
`

func (q *Queries) EdgeIDsClaimedBy(ctx context.Context, source string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, edgeIDsClaimedBy, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var edge_id int64
		if err := rows.Scan(&edge_id); err != nil {
			return nil, err
		}
		items = append(items, edge_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgesFromAll = `-- name: EdgesFromAll :many
SELECT id, source_id, target_id, type, properties, revision, created_at
FROM edges WHERE source_id = ? ORDER BY id
`

func (q *Queries) EdgesFromAll(ctx context.Context, sourceID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, edgesFromAll, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Type,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgesFromTyped = `-- name: EdgesFromTyped :many
SELECT id, source_id, target_id, type, properties, revision, created_at
FROM edges WHERE source_id = ? AND type IN (/*SLICE:types*/?) ORDER BY id
`

type EdgesFromTypedParams struct {
	SourceID string
	Types    []string
}

func (q *Queries) EdgesFromTyped(ctx context.Context, arg EdgesFromTypedParams) ([]Edge, error) {
	query := edgesFromTyped
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SourceID)
	if len(arg.Types) > 0 {
		for _, v := range arg.Types {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:types*/?", strings.Repeat(",?", len(arg.Types))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:types*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Type,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgesToAll = `-- name: EdgesToAll :many
SELECT id, source_id, target_id, type, properties, revision, created_at
FROM edges WHERE target_id = ? ORDER BY id
`

func (q *Queries) EdgesToAll(ctx context.Context, targetID string) ([]Edge, error) {
	rows, err := q.db.QueryContext(ctx, edgesToAll, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Type,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const edgesToTyped = `-- name: EdgesToTyped :many
SELECT id, source_id, target_id, type, properties, revision, created_at
FROM edges WHERE target_id = ? AND type IN (/*SLICE:types*/?) ORDER BY id
`

type EdgesToTypedParams struct {
	TargetID string
	Types    []string
}

func (q *Queries) EdgesToTyped(ctx context.Context, arg EdgesToTypedParams) ([]Edge, error) {
	query := edgesToTyped
	var queryParams []interface{}
	queryParams = append(queryParams, arg.TargetID)
	if len(arg.Types) > 0 {
		for _, v := range arg.Types {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:types*/?", strings.Repeat(",?", len(arg.Types))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:types*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(
			&i.ID,
			&i.SourceID,
			&i.TargetID,
			&i.Type,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDomain = `-- name: GetDomain :one
SELECT id, description, layers, revision, created_at FROM domains WHERE id = ?
`

func (q *Queries) GetDomain(ctx context.Context, id string) (Domain, error) {
	row := q.db.QueryRowContext(ctx, getDomain, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Layers,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const getEdge = `-- name: GetEdge :one
SELECT id, source_id, target_id, type, properties, revision, created_at FROM edges WHERE id = ?
`

func (q *Queries) GetEdge(ctx context.Context, id int64) (Edge, error) {
	row := q.db.QueryRowContext(ctx, getEdge, id)
	var i Edge
	err := row.Scan(
		&i.ID,
		&i.SourceID,
		&i.TargetID,
		&i.Type,
		&i.Properties,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const getNode = `-- name: GetNode :one
SELECT id, domain, layer, name, parent_id, source, properties, revision, created_at, updated_at
FROM nodes WHERE id = ?
`

func (q *Queries) GetNode(ctx context.Context, id string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Domain,
		&i.Layer,
		&i.Name,
		&i.ParentID,
		&i.Source,
		&i.Properties,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeRevision = `-- name: GetNodeRevision :one
SELECT revision FROM nodes WHERE id = ?
`

func (q *Queries) GetNodeRevision(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNodeRevision, id)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getSource = `-- name: GetSource :one
SELECT id, description, trust, first_seen, last_seen FROM sources WHERE id = ?
`

func (q *Queries) GetSource(ctx context.Context, id string) (Source, error) {
	row := q.db.QueryRowContext(ctx, getSource, id)
	var i Source
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.Trust,
		&i.FirstSeen,
		&i.LastSeen,
	)
	return i, err
}

const listDomains = `-- name: ListDomains :many
SELECT id, description, layers, revision, created_at FROM domains ORDER BY id
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.QueryContext(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Layers,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgeClaims = `-- name: ListEdgeClaims :many
SELECT edge_id, source, claimed_at FROM edge_claims WHERE edge_id = ? ORDER BY source
`

func (q *Queries) ListEdgeClaims(ctx context.Context, edgeID int64) ([]EdgeClaim, error) {
	rows, err := q.db.QueryContext(ctx, listEdgeClaims, edgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EdgeClaim{}
	for rows.Next() {
		var i EdgeClaim
		if err := rows.Scan(&i.EdgeID, &i.Source, &i.ClaimedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, domain, layer, name, parent_id, source, properties, revision, created_at, updated_at
FROM nodes
WHERE (?1 = '' OR domain = ?1)
  AND (?2  = '' OR layer  = ?2)
  AND (?3 = '' OR source = ?3)
ORDER BY id
LIMIT CASE WHEN ?4 = 0 THEN -1 ELSE ?4 END
`

type ListNodesParams struct {
	DomainFilter interface{}
	LayerFilter  interface{}
	SourceFilter interface{}
	Lim          interface{}
}

func (q *Queries) ListNodes(ctx context.Context, arg ListNodesParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodes,
		arg.DomainFilter,
		arg.LayerFilter,
		arg.SourceFilter,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Layer,
			&i.Name,
			&i.ParentID,
			&i.Source,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSources = `-- name: ListSources :many
SELECT id, description, trust, first_seen, last_seen FROM sources ORDER BY id
`

func (q *Queries) ListSources(ctx context.Context) ([]Source, error) {
	rows, err := q.db.QueryContext(ctx, listSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Source{}
	for rows.Next() {
		var i Source
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Trust,
			&i.FirstSeen,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nodesOwnedBy = `-- name: NodesOwnedBy :many
SELECT id, domain, layer, name, parent_id, source, properties, revision, created_at, updated_at
FROM nodes WHERE domain = ? AND source = ? ORDER BY id
`

type NodesOwnedByParams struct {
	Domain string
	Source string
}

func (q *Queries) NodesOwnedBy(ctx context.Context, arg NodesOwnedByParams) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, nodesOwnedBy, arg.Domain, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Domain,
			&i.Layer,
			&i.Name,
			&i.ParentID,
			&i.Source,
			&i.Properties,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEdgeClaim = `-- name: RemoveEdgeClaim :exec
DELETE FROM edge_claims WHERE edge_id = ? AND source = ?
`

type RemoveEdgeClaimParams struct {
	EdgeID int64
	Source string
}

func (q *Queries) RemoveEdgeClaim(ctx context.Context, arg RemoveEdgeClaimParams) error {
	_, err := q.db.ExecContext(ctx, removeEdgeClaim, arg.EdgeID, arg.Source)
	return err
}

const updateEdgeProperties = `-- name: UpdateEdgeProperties :exec
UPDATE edges SET properties = ?, revision = revision + 1 WHERE id = ?
`

type UpdateEdgePropertiesParams struct {
	Properties string
	ID         int64
}

func (q *Queries) UpdateEdgeProperties(ctx context.Context, arg UpdateEdgePropertiesParams) error {
	_, err := q.db.ExecContext(ctx, updateEdgeProperties, arg.Properties, arg.ID)
	return err
}

const updateNode = `-- name: UpdateNode :exec
UPDATE nodes SET name = ?, properties = ?, revision = revision + 1, updated_at = ?
WHERE id = ?
`

type UpdateNodeParams struct {
	Name       string
	Properties string
	UpdatedAt  int64
	ID         string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) error {
	_, err := q.db.ExecContext(ctx, updateNode,
		arg.Name,
		arg.Properties,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateSource = `-- name: UpdateSource :exec
UPDATE sources SET description = ?, trust = ? WHERE id = ?
`

type UpdateSourceParams struct {
	Description *string
	Trust       int64
	ID          string
}

func (q *Queries) UpdateSource(ctx context.Context, arg UpdateSourceParams) error {
	_, err := q.db.ExecContext(ctx, updateSource, arg.Description, arg.Trust, arg.ID)
	return err
}

const upsertEdge = `-- name: UpsertEdge :one
INSERT INTO edges(source_id, target_id, type, properties, revision, created_at)
VALUES (?, ?, ?, ?, 1, ?)
ON CONFLICT(source_id, target_id, type) DO UPDATE SET source_id = excluded.source_id
RETURNING id
`

type UpsertEdgeParams struct {
	SourceID   string
	TargetID   string
	Type       string
	Properties string
	CreatedAt  int64
}

func (q *Queries) UpsertEdge(ctx context.Context, arg UpsertEdgeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertEdge,
		arg.SourceID,
		arg.TargetID,
		arg.Type,
		arg.Properties,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSource = `-- name: UpsertSource :exec
INSERT INTO sources(id, description, trust, first_seen, last_seen)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET last_seen = excluded.last_seen
`

type UpsertSourceParams struct {
	ID          string
	Description *string
	Trust       int64
	FirstSeen   int64
	LastSeen    int64
}

func (q *Queries) UpsertSource(ctx context.Context, arg UpsertSourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertSource,
		arg.ID,
		arg.Description,
		arg.Trust,
		arg.FirstSeen,
		arg.LastSeen,
	)
	return err
}
